### ISSUE TITLE
Is a Footstone convenience class needed? 

### ISSUE THREAD

**Issue by Stephen-Gates** [muninn/graves#21]
At Toowong Cemetery we have a number of graves with [both Headstones and Footstones](https://stephen-gates.github.io/fotc/cemetery/history/#1881-queenslands-oldest-surviving-headstones).

Is there any value in having a Footstone convenience class that redirects to Tombstone, or should that detail be captured in another way?

**Comment by rwarren2** [comment]
The [image](https://en.wikipedia.org/wiki/Footstone#/media/File:Gravestones_at_Snailwell_-_geograph.org.uk_-_1067272.jpg) on the [wikipedia page for footstone](https://en.wikipedia.org/wiki/Footstone) shows an example of a grave with both footstone and gravestone, so I am going to create a new term for this object.

**Comment by rwarren2** [comment]
Created #Footstone as a subclass of #Tombstone, now disjoint with #Headstone which is now also a subclass of #Tombstone
